name: CD
on:
  repository_dispatch:
    types:
      - release_created
  push:
    branches:
      - master
      - develop

jobs:

  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - uses: nyaascii/package-version@v1
    - uses: haya14busa/action-cond@v1
      id: docker_tag
      with:
        cond: ${{ github.event.action == 'release_created' }}
        if_true: ${{ env.PACKAGE_VERSION }}
        if_false: latest
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: filipowm
        password: ${{ secrets.DOCKER_REGISTRY_PASS }}
        repository: filipowm/boogi
        tags: ${{ steps.docker_tag.outputs.value }}
        tag_with_ref: true
        tag_with_sha: true 
        always_pull: false
        cache_froms: node:buster-slim
        add_git_labels: true
        push: true # optional, default is true 
  
  npm:
    name: Publish to NPM registry
    runs-on: ubuntu-latest
    if: github.event.action == 'release_created'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
    - uses: bahmutov/npm-install@v1
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_REGISTRY_TOKEN }}
