name: CI
on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      # - name: eslint
      #   uses: reviewdog/action-eslint@v1
      #   with:
      #     reporter: github-pr-review # Change reporter.
      #     eslint_flags: 'src/'
      - name: Dockerfile
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          level: warning

  docker:
    name: Build Docker images
    runs-on: ubuntu-latest
   
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: filipowm
        password: ${{ secrets.DOCKER_REGISTRY_PASS }}
        repository: filipowm/boogi
        tags: latest
        tag_with_ref: true
        tag_with_sha: false 
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: 'Dockerfile'
        always_pull: false
        cache_froms: node:buster-slim
        add_git_labels: true
        push: false # optional, default is true 
